# Generated by Django 3.2.5 on 2021-08-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
