# Generated by Django 3.2.5 on 2021-08-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0002_alter_producto_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='appPrincipal/static/img'),
        ),
    ]
